# Generated by Django 4.0.4 on 2022-10-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email registrado previamente.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
